---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    facing: worker
    service: tgnames
    type: redis
  name: tgnames-redis-v1
spec:
  replicas: 1
  selector:
    service: tgnames
    type: redis
    version: v1
  template:
    metadata:
      labels:
        service: tgnames
        type: redis
        version: v1
    spec:
      containers:
        -
          image: redis
          imagePullPolicy: Always
          name: tgnames-redis
          cmd: ["redis"]
          args: ["redis-server","--appendonly","yes"]
          ports:
            -
              containerPort: 6379
              name: redis
              protocol: TCP
          volumeMounts:
            -
              mountPath: /data
              name: tgnames-redis-pv
          livenessProbe:
                exec:
                  command:
                  - redis-cli
                  - INFO
                initialDelaySeconds: 15
                timeoutSeconds: 1
      restartPolicy: Always
      volumes:
        -
          gcePersistentDisk:
            fsType: ext4
            pdName: tgnames-redis-pv
          name: tgnames-redis-pv