---
apiVersion: v1
kind: Service
metadata:
  labels:
    facing: worker
    service: tgnames
    type: redis
  name: tgnames-redis
spec:
  ports:
    -
      name: redis
      port: 6379
      protocol: TCP
      targetPort: redis
  selector:
    service: tgnames
    type: redis