---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    facing: worker
    service: tgnames
    type: stupid-twitter-bot
  name: tgnames-stpdbot
spec:
  replicas: 1
  selector:
    name: tgnames-stpdbot
  template:
    metadata:
      labels:
        name: tgnames-stpdbot
    spec:
      containers:
        -
          image: quay.io/purplebooth/trans-group-name-bot:latest
          imagePullPolicy: Always
          name: tgnames-stpdbot
          env:
            - name: SECRETS_PATH
              value: /secrets/trans-group-name-bot.cfg
            - name: WORDLIST_KEY
              value: tgnames
            - name: REDIS_ENV_TUTUM_SERVICE_HOSTNAME
              value: tgnames-redis
          volumeMounts:
            -
              mountPath: /secrets
              name: twitter-secrets
      restartPolicy: Always
      volumes:
        -
          name: twitter-secrets
          secret:
            secretName: twitter-secrets
